### ISSUE TITLE
Specification of gcloud_directory not working

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/gcloud-maven-plugin#8]
specifying in `pom.xml` via:

```
<plugin>
  <groupId>com.google.appengine</groupId>
  <artifactId>gcloud-maven-plugin</artifactId>
  <version>${appengine.target.version}</version>
  <configuration>
    <gcloud_directory>${gcloud.directory}</gcloud_directory>
  </configuration>
</plugin>

```

Currently still results in Unknown Google Cloud SDK location error.

Specifying via command line: `mvn gcloud:deploy -Dgcloud.gcloud_directory=$GCLOUD_PATH` also results in the same error.

**Comment by ajessup** [comment]
I also see this

**Comment by ajessup** [comment]
When running with -X I see:

[DEBUG] Configuring mojo com.google.appengine:gcloud-maven-plugin:1.9.17a:deploy from plugin realm ClassRealm[plugin>com.google.appengine:gcloud-maven-plugin:1.9.17a, parent: sun.misc.Launcher$AppClassLoader@3f99bd52]
[DEBUG] Configuring mojo 'com.google.appengine:gcloud-maven-plugin:1.9.17a:deploy' with basic configurator -->
[DEBUG]   (f) docker_cert_path = ENV_or_default
[DEBUG]   (f) docker_host = ENV_or_default
[DEBUG]   (f) docker_tls_verify = ENV_or_default
[DEBUG]   (f) gcloud_directory = /usr/local/bin/gcloud
[DEBUG]   (f) maven_project = MavenProject: com.google.appengine.demos:guestbook-stage3:1.0-SNAPSHOT @ /var/jenkins/workspace/deploy-from-maven/pom.xml
[DEBUG] -- end configuration --
[INFO] 
[INFO] Running gcloud app deploy...
[ERROR] Cannot determine the location of the Google Cloud SDK.
[ERROR] You can set it via <gcloud_directory> </gcloud_directory> in the pom.xml
[INFO] If you need to install the Google Cloud SDK, follow the instructions located at https://cloud.google.com/appengine/docs/java/managed-vms

In this case, /usr/local/bin/gcloud is a symlink to the gcloud binary at 

I get this error both when <gcloud_directory> is added to the pom.xml file or via the command line: `mvn gcloud:deploy -Dgcloud.gcloud_directory=$GCLOUD_PATH`

**Comment by ludoch** [comment]
Not sure about symlink support yet...

Can you try again with the latest plugin version?
.0.9.57.v20150425


See the latest plugin doc for the latest version.

If this does not work, try to reference the symlink for now.

**Comment by ludoch** [comment]
Doc:https://cloud.google.com/appengine/docs/java/managed-vms/maven

**Comment by ludoch** [comment]
It works for me with or without symlink.
Now, you need to pass the installation directory path, not the path to the gcloud binary executable

**Comment by karankalra** [comment]
I have been following the steps as given here: https://cloud.google.com/appengine/docs/java/managed-vms/maven
 
This is the error that I have been getting:
Failed to execute goal com.google.appengine:gcloud-maven-plugin:0.9.58.v20150505:run (default-cli) on project appengine-modules-guestbook: Execution error: java.util.NoSuchElementException

I have also tried using different versions of the gcloud-maven-plugin as given here: http://mirrors.ibiblio.org/maven2/com/google/appengine/gcloud-maven-plugin/, but nothing has helped.

Could you please help me out?

Thanks in advance.

**Comment by ludoch** [comment]
Should be addressed now with latest version.

**Comment by silentsnooc** [comment]
I just downloaded the plugin. The version I am using is

```xml
<gcloud.plugin.version>2.0.9.111.v20160525</gcloud.plugin.version>
```

but I still get this error

```xml
<plugin>
	<groupId>com.google.appengine</groupId>
	<artifactId>gcloud-maven-plugin</artifactId>
	<!-- again, no version here -->
	<configuration>
		<gcloud_directory>${gcloud.directory}</gcloud_directory>
		<set_default>true</set_default>
	</configuration>
</plugin>
```

**Comment by ludoch** [comment]
Where <gcloud.plugin.version>2.0.9.111.v20160525</gcloud.plugin.version> is
used in the plugin declaration?

I would try:

<plugin>
    <groupId>com.google.appengine</groupId>
    <artifactId>gcloud-maven-plugin</artifactId>
<version>2.0.9.111.v20160525</version>

    <configuration>
        <gcloud_directory>${gcloud.directory}</gcloud_directory>
        <set_default>true</set_default>
    </configuration>
</plugin>
